- name: Restart a container
  community.docker.docker_container:
    name: mysql
    image: mysql
    state: started
    # restart: true
    # links:
    #   - "myredis:aliasedredis"
    # devices:
    #   - "/dev/sda:/dev/xvda:rwm"
    ports:
     # Publish container port 9000 as host port 8080
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD=password